### PR TITLE
Added description for using U7 spamfilter alongside this repos scripts

### PR DESCRIPTION
**Pull request by DerZyklop**
The idea for this change came up with the discussion in https://github.com/bhopmann/uberspace7-mailfilter/issues/4 .

Since i’m not a native speaker, feel free to correct unclean grammar in the README changes.
✌

### CODE REVIEW

**Comment by bhopmann** [comment]
Thank you for your PR – I finally found the time to have a look at the U7 spamfilter specifica. 
If I understand it correctly, with help from the file `/opt/uberspace/etc/spamfolder.template` filtering by spam score is triggered and sorting via sieve is made. Therefore adding `include "$HOME/.spamfolder"` within `.mailfilter` might be unnecessary or could even have unwanted side effects.
So shouldn't activating Uberspace's own spam filter be an alternative rather than an additional option? What do you think (because I have not tested the U7 spamfilter yet)?

**Comment by DerZyklop** [comment]
You suggest to _activate_ Uberspace‘s spam filter. There is a [uberspace script](https://manual.uberspace.de/mail-spam.html) for activating it. The script does basically two things:
- crate a **.spamfolder** file which includes nothing else than a relation to the global spam filter script file **/opt/uberspace/etc/spamfolder.template**
- edit the qmail file to `|maildrop /home/your-uberspace-name/.spamfolder`

But you need to have `|maildrop /home/your-uberspace-name/.mailfilter` in the qmail file if you want to activate the **uberspace7-mailfilter** repo scripts. ◀ Correct me if I‘m wrong with this.

If I run the command `uberspace mail spamfolder enable` I will probably lose my bogofilter and therefore the ability to train my personal spam filter. The spam filter solution provided by uberspace still does not provide a way to recategorize spam and ham.
So my idea was: Since the qmail file doe’s not have the Uberspace spam filter script anymore I need to place it somewhere in my new `.mailfilter` file.

I don’t understand the content of the **spamfolder.template** file completely - thus i can not assess if including it additionally is unnecessary or if it could have possible side effects. 

So my answer to your question is: 
_For me, who wants the ability to recategorize spam and ham, the Uberspace filter is not an alternative to the bogofilter. I could probably renounce but not rely only on the Uberspace filter._

**Comment by DerZyklop** [comment]
Damn. I have tested it for some time now and I think i found a problem. 

It seems like the handlespam script does not get any mail if uberspace’s spam filter already looked at the mails. I guess it would be necessary to have a own spamfolder script instead of using uberspace’s default spamfolder.template.

To be honest: I think I will not continue to investigate here since my bogofilter/rspamd setup is working great without uberspace’s filter. Maybe i will continue if anyone stumbles upon this pull request who is searching for solutions in this subject.

**Comment by bhopmann** [comment]
@DerZyklop Never mind ;-) 
It was worth trying to integrate the U7-spamfolder - and it is even worth keeping an eye on the development of the sieve filter (cause maildrop might be obsolete) and any learning capability of the uberspace spam infrastructure, that probably might come in the future.

**Pull request closed without merging**
